name: Compile Userscript
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install Dependencies
        run: |
          npm install --global yarn
          yarn global add typescript

      - name: Compile typescript
        run: tsc

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: userscript
          path: ./snapenhance.user.js

          
